export const partsOfSpeech = [
  { value: "", label: "Select part of speech" },
  { value: "noun", label: "Noun" },
  { value: "pronoun", label: "Pronoun" },
  { value: "verb", label: "Verb" },
  { value: "adjective", label: "Adjective" },
  { value: "adverb", label: "Adverb" },
  { value: "preposition", label: "Preposition" },
  { value: "conjunction", label: "Conjunction" },
  { value: "interjection", label: "Interjection" },
  { value: "determiner", label: "Determiner" },
  { value: "other", label: "Other" },
];

export const TypologyFieldTitles = {
  word_order: "Word Order",
  morphosyntactic_alignment: "Morphosyntactic Alignment",
  language_family: "Language Family",
  verbal_tenses: "Verbal Tenses",
  type_morphology: "Type of Morphology",
  pro_drop: "Pro-drop",
  formality_system: "Formality System",
  vowel_inventory: "Vowel Inventory",
  tonal: "Tonal",
  syllable_structure: "Syllable Structure",
};

export const TypologySchema = {
  word_order: [
    "SVO",
    "SOV",
    "VSO",
    "VOS",
    "OVS",
    "OSV",
    "No Default Word Order",
    "Pragmatic Word Order",
  ],
  morphosyntactic_alignment: [
    "Nominative-Accusative",
    "Ergative-Absolutive",
    "Tripartite",
    "Austronesian/Arusian-like",
    "Other",
  ],
  language_family: [
    "Indo-European",
    "Sino-Tibetan",
    "Afro-Asiatic",
    "Niger-Congo",
    "Austronesian",
    "Dravidian",
    "Turkic",
    "Uralic",
    "Other",
  ],
  verbal_tenses: [
    "Present, Past, Future",
    "Past, Non-Past",
    "Present, Non-Present",
    "No Tenses",
    "Other",
  ],
  type_morphology: [
    "Analytic",
    "Synthetic",
    "Agglutinative",
    "Isolating",
    "Non-Concatenative",
    "Mixed",
  ],
  pro_drop: [
    "No",
    "Partial",
    "Yes (Only the Subject)",
    "Yes (Both Subject and Object)",
    "Yes (Only the Object)",
  ],
  formality_system: [
    "T-V Distinction",
    "Honorifics",
    "Mixed",
    "No Formality Distinctions",
  ],
  vowel_inventory: [
    "No Length and Nasality",
    "Long and Short Vowels",
    "Presence of Nasalization",
    "Long, Short and Nasal Vowels",
    "Complex",
  ],
  tonal: ["Tonal", "Non-Tonal", "Pitch Accent"],
  syllable_structure: ["CV", "CVC", "CCV", "CCVC", "Complex"],
};
